version: '3'

services:
  db:
    build: ./database
    image: tgrande/mysql:latest # Using the official image directly without a custom Dockerfilen
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student_grades
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    ports:
      - "3306:3306"
    networks:
      - app-network # Ensuring all services are on the same network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "exit 0"

  web-app:
    build: ./web-app
    image: tgrande/web-app:latest
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user1
      MYSQL_DB: student_grades
      MYSQL_PASSWORD: password1
    depends_on:
      - db
      - auth-service
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    image: tgrande/auth-service:latest
    ports:
      - "5001:5001"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    networks:
      - app-network
    ports:
      - "27017:27017"
    depends_on:
      - db
    healthcheck:
      test: "exit 0"

  data-transfer:
    build: ./data-transfer
    image: tgrande/data-transfer:latest
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

  data-display:
    build: ./data-display
    image: tgrande/data-display:latest
    ports:
      - "5002:5002"
    networks:
      - app-network
    depends_on:
      - auth-service
      - mongo

networks:
  app-network:
    driver: bridge
