apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transfer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-transfer
  template:
    metadata:
      labels:
        app: data-transfer
    spec:
      containers:
      - name: data-transfer
        image: tgrande/data-transfer:latest
        # Add resource requests/limits and environment variables here if needed