apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-display-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-display
  template:
    metadata:
      labels:
        app: data-display
        service-group: web-group 
    spec:
      containers:
      - name: data-display
        image: tgrande/data-display:latest
        ports:
        - containerPort: 5002

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: data-display-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: data-display
#   ports:
#   - port: 5002
#     targetPort: 5002
