apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-display-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-display
  template:
    metadata:
      labels:
        app: data-display
    spec:
      containers:
      - name: data-display
        image: tgrande/data-display:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: data-display-service
spec:
  type: NodePort
  selector:
    app: data-display
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
