apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tgrande/web-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql-deployment"
        - name: MYSQL_USER
          value: "user1"
        - name: MYSQL_PASSWORD
          value: "password1"
        - name: MYSQL_DB
          value: "student_grades"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30003
